name: riverpod_app
description: RiverPod Example project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^1.22.0
  firebase_auth: ^3.8.0
  retrofit: ^3.0.1+1
  json_annotation:
  logger: ^1.1.0
  dio: ^4.0.6
  flutter_riverpod: ^1.0.4
  hive_flutter: ^1.1.0
  cloud_firestore: ^3.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^1.1.3
  retrofit_generator: ^4.0.3+1
  json_serializable: ^6.3.1
  build_runner: ^2.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svg/