// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV7KJSyQ-EvNud3M9bGu4VGSR0M-tVlp8',
    appId: '1:991135240586:web:6f2ccab4d917e7004cb873',
    messagingSenderId: '991135240586',
    projectId: 'riverpod-application',
    authDomain: 'riverpod-application.firebaseapp.com',
    databaseURL:
        'https://riverpod-application-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'riverpod-application.appspot.com',
    measurementId: 'G-2SRHDJKRPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtD3ZjUtmPlBWb1LKu5qsWKynV_oPiXzk',
    appId: '1:991135240586:android:f365103eba0dcb644cb873',
    messagingSenderId: '991135240586',
    projectId: 'riverpod-application',
    databaseURL:
        'https://riverpod-application-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'riverpod-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVtwNBgCkmKajCAU1cJP6FqmipQZF5ckI',
    appId: '1:991135240586:ios:f14ab19bd3b8db844cb873',
    messagingSenderId: '991135240586',
    projectId: 'riverpod-application',
    databaseURL:
        'https://riverpod-application-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'riverpod-application.appspot.com',
    androidClientId:
        '991135240586-onv5o49j6fb8pab6t5fk33vqri17icp9.apps.googleusercontent.com',
    iosClientId:
        '991135240586-13fmrah9ufldjc01aicivu5b497clj21.apps.googleusercontent.com',
    iosBundleId: 'com.septware.riverpodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVtwNBgCkmKajCAU1cJP6FqmipQZF5ckI',
    appId: '1:991135240586:ios:f14ab19bd3b8db844cb873',
    messagingSenderId: '991135240586',
    projectId: 'riverpod-application',
    databaseURL:
        'https://riverpod-application-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'riverpod-application.appspot.com',
    androidClientId:
        '991135240586-onv5o49j6fb8pab6t5fk33vqri17icp9.apps.googleusercontent.com',
    iosClientId:
        '991135240586-13fmrah9ufldjc01aicivu5b497clj21.apps.googleusercontent.com',
    iosBundleId: 'com.septware.riverpodApp',
  );
}
